Feature to add logical roles
KarlOfDuty/SCPDiscord pull request #178
Opened 2024-09-14 13:21 UTC by TiBarification

More complex system of role check.

More details from #175

2024-09-14 13:25 UTC, TiBarification commented on SCPDiscordPlugin/LogicRole.cs
> +				LogicType.None => true,
Oops, here should be false. Means we never go execute commands and go into childrens

2024-09-17 13:35 UTC, KarlOfDuty requested changes
This system is way too complicated, you need to either simplify it or change the config to be much easier to understand.

2024-09-17 13:46 UTC, TiBarification commented
Its purpose is not to simplify, but to make it more flexible in management. I think I will close pr then because it doesn't correlate with your view.

2024-09-17 13:53 UTC, KarlOfDuty commented
I understand that, but most people only want to sync specific roles to the game, not combinations of roles. The system you have created makes it much more complicated to configure for everyone, and only a small number of people will need it.

2024-09-17 14:03 UTC, closed without merging